"""The session report as a PDF, laid out server-side.

fpdf2 with the built-in Helvetica, so there are no font files to ship. The
cost is Latin-1: text written by the model is full of em dashes and curly
quotes, so everything is folded to plain ASCII on the way in rather than
raising halfway down a page.

The layout follows the report screen (scores, themes, identity, attention, then
the per-question breakdown) so the printed page matches what was on screen.
"""

from datetime import datetime

from fpdf import FPDF

from app.services.cv_analysis import STATE_LABELS

# Approximates the app's palette (frontend/src/styles/tokens.css).
INK = (24, 28, 34)
MUTED = (107, 114, 128)
RULE = (226, 230, 236)
ACCENT = (161, 92, 0)
SIGNAL = (15, 125, 104)
DANGER = (180, 35, 24)

ROLE_LABELS = {
    "SDE": "Software Development Engineer",
    "DS": "Data Scientist",
    "MLE": "ML Engineer",
    "QA": "QA / Test Engineer",
    "PM": "Product Manager",
    "HR": "HR / Behavioural",
}

RUBRIC_LABELS = {
    "correctness": "Correctness",
    "depth": "Depth",
    "relevance": "Relevance",
    "clarity": "Clarity",
}

IDENTITY_STATUS_LABELS = {
    "verified": "Verified",
    "flagged": "Flagged",
    "inconclusive": "Inconclusive",
    "not_verified": "Not verified",
}

# Characters a language model reaches for that Helvetica can't draw.
_REPLACEMENTS = {
    "\u2014": "-", "\u2013": "-", "\u2018": "'", "\u2019": "'",
    "\u201c": '"', "\u201d": '"', "\u2026": "...", "\u2022": "-",
    "\u00a0": " ", "\u2192": "->",
}


def _text(value) -> str:
    text = str(value or "")
    for source, target in _REPLACEMENTS.items():
        text = text.replace(source, target)
    return text.encode("latin-1", "ignore").decode("latin-1")


class _Report(FPDF):
    def footer(self) -> None:
        self.set_y(-14)
        self.set_font("Helvetica", size=7)
        self.set_text_color(*MUTED)
        self.cell(
            0,
            4,
            _text(
                "Generated by ARIA on this machine - no audio, video or images were stored. "
                f"Page {self.page_no()}"
            ),
            align="C",
        )


def _rule(pdf: _Report, gap: float = 3.0) -> None:
    pdf.ln(gap)
    pdf.set_draw_color(*RULE)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
    pdf.ln(gap)


def _heading(pdf: _Report, text: str) -> None:
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(*INK)
    pdf.cell(0, 7, _text(text), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(1)


def _para(pdf: _Report, text: str, *, size: float = 9.5, colour=None, indent: float = 0) -> None:
    pdf.set_font("Helvetica", size=size)
    pdf.set_text_color(*(colour or INK))
    if indent:
        pdf.set_x(pdf.l_margin + indent)
    # multi_cell leaves the cursor to the *right* of the block by default, which
    # sends whatever is written next off the edge of the page.
    pdf.multi_cell(
        pdf.w - pdf.l_margin - pdf.r_margin - indent,
        4.8,
        _text(text),
        align="L",
        new_x="LMARGIN",
        new_y="NEXT",
    )


def _label(pdf: _Report, text: str) -> None:
    pdf.set_font("Helvetica", "B", 7.5)
    pdf.set_text_color(*MUTED)
    pdf.cell(0, 4.5, _text(text.upper()), new_x="LMARGIN", new_y="NEXT")


def _score_row(pdf: _Report, tiles: list[tuple[str, float | None, str]]) -> None:
    width = (pdf.w - pdf.l_margin - pdf.r_margin) / len(tiles)
    top = pdf.get_y()
    for position, (label, value, hint) in enumerate(tiles):
        x = pdf.l_margin + width * position
        pdf.set_xy(x, top)
        pdf.set_font("Helvetica", "B", 7.5)
        pdf.set_text_color(*MUTED)
        pdf.cell(width, 4.5, _text(label.upper()), new_x="LEFT", new_y="NEXT")
        pdf.set_x(x)
        pdf.set_font("Helvetica", "B", 20)
        pdf.set_text_color(*INK)
        pdf.cell(width, 9, "-" if value is None else str(round(value)), new_x="LEFT", new_y="NEXT")
        pdf.set_x(x)
        pdf.set_font("Helvetica", size=7)
        pdf.set_text_color(*MUTED)
        pdf.multi_cell(width - 4, 3.4, _text(hint), align="L", new_x="LMARGIN", new_y="NEXT")
    pdf.set_y(top + 22)


def _bullets(pdf: _Report, title: str, items: list[str], empty: str) -> None:
    _label(pdf, title)
    if not items:
        _para(pdf, empty, colour=MUTED)
        return
    for item in items:
        pdf.set_font("Helvetica", size=9.5)
        pdf.set_text_color(*INK)
        pdf.cell(4, 4.8, "-")
        pdf.multi_cell(
            pdf.w - pdf.l_margin - pdf.r_margin - 4,
            4.8,
            _text(item),
            align="L",
            new_x="LMARGIN",
            new_y="NEXT",
        )
    pdf.ln(1)


def _identity_section(pdf: _Report, identity: dict) -> None:
    _heading(pdf, "Identity verification")
    status = identity.get("status") or "not_verified"
    method = "Resume photo" if identity.get("method") == "resume_photo" else "Camera verification"
    pdf.set_font("Helvetica", "B", 9.5)
    pdf.set_text_color(*(SIGNAL if status == "verified" else DANGER if status == "flagged" else ACCENT))
    pdf.cell(0, 5, _text(IDENTITY_STATUS_LABELS.get(status, status)), new_x="LMARGIN", new_y="NEXT")
    _para(pdf, f"{method} - {identity.get('checks', 0)} checks, {identity.get('matches', 0)} matched, "
               f"{identity.get('mismatches', 0)} mismatched, {identity.get('multiple_faces', 0)} with more "
               f"than one face, {identity.get('face_not_detected', 0)} with no face.", colour=MUTED)
    if identity.get("status_reason"):
        _para(pdf, identity["status_reason"])
    for event in identity.get("events", []):
        _para(pdf, f"- {event.get('type', '').replace('_', ' ').title()} ({event.get('checks', 0)} checks)",
              size=9, colour=MUTED, indent=2)


def _attention_section(pdf: _Report, attention: dict) -> None:
    _heading(pdf, "Attention & gaze")
    shares = attention.get("shares", {})
    _para(
        pdf,
        f"Eye contact {round(attention.get('on_camera_share', 0))}% across "
        f"{attention.get('checks', 0)} camera checks.",
    )
    away = ", ".join(
        f"{STATE_LABELS.get(state, state).lower()} {round(share)}%"
        for state, share in shares.items()
        if state != "on_camera"
    )
    if away:
        _para(pdf, f"The rest: {away}.", colour=MUTED)
    if attention.get("note"):
        _para(pdf, attention["note"])
    for episode in attention.get("episodes", []):
        _para(pdf, f"- {episode['label']} for about {round(episode['seconds'])}s",
              size=9, colour=MUTED, indent=2)


def _question_section(pdf: _Report, session: dict, answered: list[dict]) -> None:
    _heading(pdf, "Question breakdown")
    turns = (session.get("conversation") or {}).get("turns", [])

    for number, question in enumerate(answered, 1):
        if pdf.will_page_break(40):
            pdf.add_page()
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(*INK)
        pdf.cell(
            0,
            5.5,
            _text(f"Q{number}  {round(question['content_score'])}/100  -  {question.get('topic') or 'Question'} "
                  f"(difficulty {question.get('difficulty_level')})"),
            new_x="LMARGIN",
            new_y="NEXT",
        )
        _para(pdf, question.get("text", ""))

        rubric = question.get("rubric") or {}
        if rubric:
            _para(
                pdf,
                "   ".join(f"{label} {rubric.get(key, 0)}/10" for key, label in RUBRIC_LABELS.items()),
                size=9,
                colour=MUTED,
            )
        for note_key in ("delivery_note", "visual_note"):
            if question.get(note_key):
                _para(pdf, question[note_key], size=9, colour=MUTED)
        if (question.get("attention") or {}).get("note"):
            _para(pdf, question["attention"]["note"], size=9, colour=MUTED)
        if question.get("feedback_text"):
            _para(pdf, question["feedback_text"])

        thread = [
            turn
            for turn in turns
            if turn.get("question_index") == question.get("order_index")
            and turn.get("kind") != "repeat_request"
        ]
        if thread:
            _label(pdf, "the conversation")
            for turn in thread:
                speaker = "ARIA" if turn["speaker"] == "interviewer" else "You"
                _para(pdf, f"{speaker}: {turn['text']}", size=8.5, colour=MUTED, indent=3)
        pdf.ln(3)


def build(session: dict, strengths: list[str], improvements: list[str], candidate: str | None) -> bytes:
    """Render one finished session into PDF bytes."""
    pdf = _Report(format="A4")
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.set_title(_text(f"ARIA interview report - {session.get('role', '')}"))
    pdf.add_page()

    answered = [q for q in session.get("questions", []) if q.get("content_score") is not None]
    started = session.get("started_at")
    started_text = started.strftime("%d %B %Y") if isinstance(started, datetime) else ""

    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(*INK)
    pdf.cell(0, 9, "ARIA interview report", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", size=9.5)
    pdf.set_text_color(*MUTED)
    mode = "Conversational interview" if session.get("mode") == "conversation" else "One question at a time"
    pdf.cell(
        0,
        5,
        _text(
            " - ".join(
                part
                for part in (
                    candidate,
                    ROLE_LABELS.get(session.get("role"), session.get("role", "")),
                    mode,
                    f"{len(answered)} questions answered",
                    started_text,
                )
                if part
            )
        ),
        new_x="LMARGIN",
        new_y="NEXT",
    )
    _rule(pdf)

    _score_row(
        pdf,
        [
            ("Overall", session.get("overall_score"), "All measured dimensions"),
            ("Content", session.get("content_score_avg"), "Correctness, depth, relevance, clarity"),
            ("Delivery", session.get("delivery_score_avg"), "Pace, pauses, filler words"),
            ("Visual", session.get("visual_score_avg"), "Eye contact, expression, posture"),
        ],
    )
    _rule(pdf)

    _bullets(pdf, "Strengths", strengths, "No strengths were identified in this session.")
    _bullets(pdf, "Areas to improve", improvements, "Nothing flagged for improvement.")

    identity = session.get("identity")
    if identity and identity.get("required"):
        _rule(pdf)
        _identity_section(pdf, identity)

    attention = session.get("attention")
    if attention and attention.get("checks"):
        _rule(pdf)
        _attention_section(pdf, attention)

    _rule(pdf)
    if answered:
        _question_section(pdf, session, answered)
    else:
        _heading(pdf, "Question breakdown")
        _para(pdf, "No questions were answered in this session.", colour=MUTED)

    return bytes(pdf.output())
